project_id = "heywtqzdytbsavublmhj"

[functions.post-to-telegram]
verify_jwt = false

[functions.check-prices]
verify_jwt = false

[functions.discover-products]
verify_jwt = false

[functions.detect-deals]
verify_jwt = false

[functions.process-deals]
verify_jwt = false

[functions.discover-multistore-products]
verify_jwt = false
